name: build
on: push
jobs:
  build-ubuntu-meson:
    runs-on: ubuntu-latest
    steps:
      - name: install meson
        run: sudo apt update -y && sudo apt install -y meson
      - uses: actions/checkout@v2
      - name: compile library
        run: meson build && ninja -C build
      - name: compile example
        run: meson example/build example && ninja -C example/build
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-meson
          path: |
            build/
            example/build/  build-ubuntu:
  build-ubuntu-cmake:
    runs-on: ubuntu-latest
    steps:
      - name: install ninja-build
        run: sudo apt update -y && sudo apt install -y ninja-build
      - uses: actions/checkout@v2
      - name: compile library
        run: cmake -S . -B build && cmake --build build
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-cmake
          path: |
            build/
  collect-and-release:
    needs: [build-ubuntu-meson, build-ubuntu-cmake]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact ubuntu-cmake
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-meson
    - name: Download artifact ubuntu-cmake
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-cmake
    - name: 'List what is in the working directory'
      shell: bash
      run: |
        ls -la && find .
